// eslint-disable-next-line @typescript-eslint/no-unused-vars
type CarWashInfo = {
    car_wash_id?: number; // Auto-generated by the database
    car_wash_name: string;
    registration_number: string;
    physical_address: string;
    contact_number: string;
    operating_hours: string;
    services_offered: string[];
    car_wash_joining_date: string;
  };
  